### ISSUE TITLE
Too many open files error!

### ISSUE THREAD

**Issue by xiefeinjau** [wwood/CoverM#149]
Hi, I used the nice tool CoverM for calculating the coverage of MAG (~400) and over 1500 samples, but get an error. Please give me some advice, thanks!

"thread 'main' panicked at 'Failed to create cache samtools view log tempfile: Custom { kind: Uncategorized, error: PathError { path: "/mnt/sdb/xiefei/database/coverm/.tmpbBTe08", err: Os { code: 24, kind: Uncategorized, message: "Too many open files" } } }', src/bam_generator.rs:329:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace"

**Comment by wwood** [comment]
Hi,

Thanks for the kind words.

That's a new one. Likely what is happening is due to their being many many samples, which means many mappings, which means too many log files being opened at once, so the OS complains.

I'd say this is technically a bug but is probably low priority to fix. I'd suggest just running the samples one at a time or in smaller batches should workaround it. That will mean merging the results at the end but that doesn't seem too onerous.

Thanks anyway for the report, leaving it open.

-\-------------
Ben Woodcroft
Group leader, Centre for Microbiome Research, QUT
________________________________
From: Fei Xie ***@***.***>
Sent: Friday, December 30, 2022 7:29:10 PM
To: wwood/CoverM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wwood/CoverM] Too many open files error! (Issue #149)


Hi, I used the nice tool CoverM for calculating the coverage of MAG (~400) and over 1500 samples, but get an error. Please give me some advice, thanks!

"thread 'main' panicked at 'Failed to create cache samtools view log tempfile: Custom { kind: Uncategorized, error: PathError { path: "/mnt/sdb/xiefei/database/coverm/.tmpbBTe08", err: Os { code: 24, kind: Uncategorized, message: "Too many open files" } } }', src/bam_generator.rs:329:40
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace"

―
