### ISSUE TITLE
Error message: thread 'main' panicked at 'Unable to parse version for dashing (error 1)', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bird_tool_utils-0.2.0/src/external_command_checker.rs:98:14

### ISSUE THREAD

**Issue by gecko1990** [wwood/CoverM#45]
Hi,

I installed coverM through the bioconda and I am getting the following message:

```
coverm genome -c LIBARIES -d Bins/ -x fasta --dereplicate --dereplication-output-cluster-definition Dereplicated_representatives_tab --bam-file-cache-directory tmp/ --discard-unmapped -t 20

[2020-12-03T10:49:16Z INFO  coverm] CoverM version 0.5.0
[2020-12-03T10:49:16Z INFO  coverm] Using min-covered-fraction 10%
[2020-12-03T10:49:16Z INFO  bird_tool_utils::external_command_checker] Found minimap2 version 2.17-r941
[2020-12-03T10:49:16Z INFO  bird_tool_utils::external_command_checker] Found samtools version 1.9
[2020-12-03T10:49:16Z INFO  coverm] Found 119 genomes specified before dereplication
[2020-12-03T10:49:16Z INFO  bird_tool_utils::external_command_checker] Found fastANI version 1.32
[2020-12-03T10:49:16Z WARN  galah::cluster_argument_parsing] Since CheckM input is missing, genomes are not being ordered by quality. Instead the order of their input is being used
thread 'main' panicked at 'Unable to parse version for dashing (error 1)', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bird_tool_utils-0.2.0/src/external_command_checker.rs:98:14
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:526
  11: rust_begin_unwind
             at src/libstd/panicking.rs:437
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_failed
             at src/libcore/option.rs:1261
  14: bird_tool_utils::external_command_checker::default_version_check
  15: galah::cluster_argument_parsing::generate_galah_clusterer
  16: coverm::main
  17: std::rt::lang_start::{{closure}}
  18: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  19: std::panicking::try::do_call
             at src/libstd/panicking.rs:348
  20: std::panicking::try
             at src/libstd/panicking.rs:325
  21: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  22: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  23: main
  24: __libc_start_main
  25: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

The problem does not appear when I do not perform dereplication. Could you help me solving this issue?

**Comment by wwood** [comment]
Hmm, sounds like something is wrong with your dashing installation e.g. https://github.com/dnbaker/dashing/issues/41

What happens when you run `dashing --version` ?

**Comment by wwood** [comment]
>The problem does not appear when I do not perform dereplication

BTW that is because dashing is only used for dereplication, so is not checked for when no dereplication is used

**Comment by wwood** [comment]
And as a short term solution, you can use ` --dereplication-precluster-method finch` to use a non-dashing (a little slower) method for the initial step of dereplication

**Comment by gecko1990** [comment]
> 
> 
> Hmm, sounds like something is wrong with your dashing installation e.g. [dnbaker/dashing#41](https://github.com/dnbaker/dashing/issues/41)
> 
> What happens when you run `dashing --version` ?
This is what I get... Not sure why...

```
dashing --version
Illegal instruction (core dumped)
```

**Comment by gecko1990** [comment]
> 
> 
> And as a short term solution, you can use ` --dereplication-precluster-method finch` to use a non-dashing (a little slower) method for the initial step of dereplication

This seems to work for now. I will check the result tomorrow.
