### ISSUE TITLE
Mapping errors on a cluster

### ISSUE THREAD

**Issue by r0sies** [wwood/CoverM#59]
Hi, 
I am running coverm v0.6.1, samtools/1.11, minimap2/2.17 with 16 CPUs and 96GB RAM and receive the below error with shotgun WGS data.

[2021-03-16T05:18:25Z INFO  coverm] CoverM version 0.6.1
[2021-03-16T05:18:25Z INFO  coverm] Using min-covered-fraction 10%
[2021-03-16T05:18:25Z INFO  bird_tool_utils::external_command_checker] Found minimap2 version 2.17-r941 
[2021-03-16T05:18:25Z INFO  bird_tool_utils::external_command_checker] Found samtools version 1.11 
[2021-03-16T05:18:25Z INFO  coverm] Profiling 1316 genomes
[2021-03-16T05:18:25Z INFO  coverm] Generating concatenated reference FASTA file of 1316 genomes ..
[2021-03-16T05:18:33Z INFO  coverm] Not pre-generating minimap2 index
[2021-03-16T05:18:33Z ERROR coverm::bam_generator] Failed to correctly find or parse BAM file at "/tmp/pbs.464383.pbstraining/coverm_fifo.6HZvphWYmiRQ/foo.pipe": unable 
to open SAM/BAM/CRAM file at /tmp/pbs.464383.pbstraining/coverm_fifo.6HZvphWYmiRQ/foo.pipe
[2021-03-16T05:19:47Z ERROR coverm::bam_generator] Error when running mapping process. Exitstatus was ExitStatus(ExitStatus(256)). Command run was: ["bash -c \"set -e -o
 pipefail; minimap2 --split-prefix /tmp/pbs.464383.pbstraining/.tmpUWtTHg -a -x sr  -t 16  \'/tmp/pbs.464383.pbstraining/.tmp90WfNW\' \'/project/SIH/Fastq_clea
ned_target/C10_M2_0B_R1.clean.target.fastq.gz\' \'/project/SIH/Fastq_cleaned_target/C10_M2_0B_R2.clean.target.fastq.gz\' 2>/tmp/pbs.464383.pbstraining/.tmpkT3b
A2  | remove_minimap2_duplicated_headers 2>/tmp/pbs.464383.pbstraining/.tmppj36A1| samtools sort -T \'/tmp/pbs.464383.pbstraining/coverm_fifo.6HZvphWYmiRQ/coverm-make-sa
mtools-sortMWaOYX\' -l0 -@ 15 2>/tmp/pbs.464383.pbstraining/.tmpvoDUpc > \"/tmp/pbs.464383.pbstraining/coverm_fifo.6HZvphWYmiRQ/foo.pipe\"\""]
[2021-03-16T05:19:47Z ERROR coverm::bam_generator] The STDERR for the MINIMAP2_SR part was: [M::mm_idx_gen::67.038*1.69] collected minimizers
    [M::mm_idx_gen::71.500*2.47] sorted minimizers
    
[2021-03-16T05:19:47Z ERROR coverm::bam_generator] The STDERR for the samtools sort part was: samtools sort: failed to read header from "-"
    
[2021-03-16T05:19:47Z ERROR coverm::bam_generator] The STDERR for the remove_minimap2_duplicated_headers part was: bash: remove_minimap2_duplicated_headers: command not 
found
    
[2021-03-16T05:19:47Z ERROR coverm::bam_generator] Cannot continue since mapping failed.

**Comment by wwood** [comment]
Hi, apologies for the slow response. Reading your STDERR I think the relevant bit is this:
```
[2021-03-16T05:19:47Z ERROR coverm::bam_generator] The STDERR for the remove_minimap2_duplicated_headers part was: bash: remove_minimap2_duplicated_headers: command not
found
```
This suggests coverm has not been installed correctly. CoverM comes with a binary `remove_minimap2_duplicated_headers` to fix a bug in minimap2, and this must be on the PATH. In your case, it appears not to be. I'm not sure how you installed it but does that help?

**Comment by r0sies** [comment]
Thank you. 

I reinstalled with a later version of minimap/2.3 and now come across this error: 

coverm genome --threads ${NCPUS} --genome-fasta-directory dereplicated_genomes --genome-fasta-extension fa --coupled ${r1} ${r2} > ${outdir}/abundances-${sample}.txt
[2021-04-14T05:44:01Z INFO  coverm] CoverM version 0.6.1
[2021-04-14T05:44:01Z INFO  coverm] Using min-covered-fraction 10%
[2021-04-14T05:44:01Z INFO  bird_tool_utils::external_command_checker] Found minimap2 version 2.3-r545-dirty 
thread 'main' panicked at 'Failed to find sufficient version of minimap2: "It appears the available version of minimap2 is too old (found version 2.3-r545-dirty, required is 2.17-r941)"', src/external_command_checker.rs:11:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by r0sies** [comment]
Hi, thank you. I tried with a newer release of minimap 2.17, but had this error. I'll try with 2.18 next.

coverm genome --threads ${NCPUS} \
> --genome-fasta-directory dereplicated_genomes \
> --genome-fasta-extension fa \
> --coupled \
> ${r1} ${r2} > ${outdir}/abundances-${sample}.txt
[2021-04-14T05:42:38Z INFO  coverm] CoverM version 0.6.1
[2021-04-14T05:42:38Z INFO  coverm] Using min-covered-fraction 10%
[2021-04-14T05:42:38Z INFO  bird_tool_utils::external_command_checker] Found minimap2 version 2.17-r1009-dirty 
thread 'main' panicked at 'Failed to find sufficient version of minimap2: "It appears the available version of minimap2 is too old (found version 2.17-r1009-dirty, required is 2.17-r941)"', src/external_command_checker.rs:11:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

$ module list
Currently Loaded Modulefiles:
  1) training/0.0.1    3) minimap2/2.17     5) fastani/1.32      7) bcftools/1.9      9) coverm/0.6.1
  2) dashing/0.5.6-1   4) bwa/0.7.17        6) openssl/1.1.0h    8) samtools/1.9

**Comment by wwood** [comment]
Hi,

There's a few things going wrong here:
1) minimap2 2.17 has a bug in it, which coverm implements a workaround for
2) your installation is not correct, as previous, I believe installation via conda works
3) coverm has a bug when detecting the version of minimap2, which is causing that last error.

Luckily, minimap2 2.18 has fixed the first issue, so the rest of the issues will go away, once I've released the next version of coverm. Will do soon.

I don't think just trying with 2.18 will work, because coverm will still try to run `remove_minimap2_duplicated_headers` (the workaround). Speak to your sysadmins as they do not appear to have installed coverm correctly.

**Comment by r0sies** [comment]
Thanks for this.
We have reinstalled coverm, and it runs as you have anticipated. I look forward to the next release.

Error messages for reference with minimap2 version 2.18 and 2.17-r1009-dirty

$ module list
Currently Loaded Modulefiles:
  1) training/0.0.1    3) minimap2/2.18     5) fastani/1.32      7) bcftools/1.9      9) coverm/0.6.1
  2) dashing/0.5.6-1   4) bwa/0.7.17        6) openssl/1.1.0h    8) samtools/1.9

$ minimap2 --version
2.18-r1015

$coverm genome --threads ${NCPUS} \
> --genome-fasta-directory dereplicated_genomes \
> --genome-fasta-extension fa \
> --coupled \
> ${r1} ${r2} > ${outdir}/abundances-${sample}.txt
[2021-04-14T23:26:56Z INFO  coverm] CoverM version 0.6.1
[2021-04-14T23:26:56Z INFO  coverm] Using min-covered-fraction 10%
[2021-04-14T23:26:56Z INFO  bird_tool_utils::external_command_checker] Found minimap2 version 2.18-r1015 
[2021-04-14T23:26:57Z INFO  bird_tool_utils::external_command_checker] Found samtools version 1.9 
[2021-04-14T23:26:57Z INFO  coverm] Profiling 1316 genomes
[2021-04-14T23:26:57Z INFO  coverm] Generating concatenated reference FASTA file of 1316 genomes ..
[2021-04-14T23:31:46Z INFO  coverm] Not pre-generating minimap2 index
[2021-04-14T23:31:57Z WARN  coverm::genome] No primary alignments were observed for sample C10_M2_0B_R1.clean.target.fastq.gz - perhaps something went wrong in the mapping?
[2021-04-14T23:31:57Z INFO  coverm::genome] In sample 'C10_M2_0B_R1.clean.target.fastq.gz', found 0 reads mapped out of 0 total (NaN%)
[2021-04-14T23:31:57Z ERROR coverm::bam_generator] Error when running mapping process. Exitstatus was ExitStatus(ExitStatus(25856)). Command run was: ["bash -c \"set -e -o pipefail; minimap2 --split-prefix /tmp/.tmprLwIEr -a -x sr  -t 1  \'/tmp/.tmpBuTh8T\' \'C10_M2_0B_R1.clean.target.fastq.gz\' \'C10_M2_0B_R2.clean.target.fastq.gz\' 2>/tmp/.tmpuR4tVb  | remove_minimap2_duplicated_headers 2>/tmp/.tmpFogVaP| samtools sort -T \'/tmp/coverm_fifo.QmFcFVuvWlwp/coverm-make-samtools-sortZQdWE9\' -l0 -@ 0 2>/tmp/.tmpCFpIvj > \"/tmp/coverm_fifo.QmFcFVuvWlwp/foo.pipe\"\""]
[2021-04-14T23:31:57Z ERROR coverm::bam_generator] The STDERR for the MINIMAP2_SR part was: 
[2021-04-14T23:31:57Z ERROR coverm::bam_generator] The STDERR for the samtools sort part was: 
[2021-04-14T23:31:57Z ERROR coverm::bam_generator] The STDERR for the remove_minimap2_duplicated_headers part was: thread 'main' panicked at 'After 0 lines, no @PG lines were detected - something went wrong during mapping?', src/bin/remove_minimap2_duplicated_headers.rs:44:9
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    
[2021-04-14T23:31:57Z ERROR coverm::bam_generator] Cannot continue since mapping failed.


$ module list
Currently Loaded Modulefiles:
  1) training/0.0.1    3) bwa/0.7.17        5) openssl/1.1.0h    7) samtools/1.9      9) minimap2/2.17
  2) dashing/0.5.6-1   4) fastani/1.32      6) bcftools/1.9      8) coverm/0.6.1
$ minimap2 --version
2.17-r1009-dirty


$ coverm genome --threads ${NCPUS} --genome-fasta-directory /project/CAFEM_new/SIH/iMGMC_database/dereplicated_genomes --genome-fasta-extension fa --coupled ${r1} ${r2} > ${outdir}/abundances-${sample}.txt
[2021-04-15T00:20:04Z INFO  coverm] CoverM version 0.6.1
[2021-04-15T00:20:04Z INFO  coverm] Using min-covered-fraction 10%
[2021-04-15T00:20:04Z INFO  bird_tool_utils::external_command_checker] Found minimap2 version 2.17-r1009-dirty 
thread 'main' panicked at 'Failed to find sufficient version of minimap2: "It appears the available version of minimap2 is too old (found version 2.17-r1009-dirty, required is 2.17-r941)"', src/external_command_checker.rs:11:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[TRAINING rsad8020@login1 mags]$

**Comment by wwood** [comment]
Hi again,

Unfortunately, minimap2 2.18 cannot be used with CoverM, because of a (now fixed) bug in minimap2. In the meantime I have pinned the conda release to 2.17, and updated the README's dependency section. If this is still an issue, then feel free to comment and I can reopen.

Thanks.

**Comment by susheelbhanu** [comment]
Hi, 

I have a similar issue, but I have the following minimap2 version: `2.17-r941`, and also have the `remove_minimap2_duplicated_headers` in my path. 

I'm running coverm via Snakemake and below is the header for the error file:
````
Mon May 31 09:26:23 CEST 2021
[2021-05-31T07:26:23Z INFO  coverm] CoverM version 0.6.1
[2021-05-31T07:26:23Z INFO  coverm] Writing output to file: /scratch/users/sbusi/rocks/coassembly/binning/results/coverage/coassembly_covstats.txt
[2021-05-31T07:26:23Z INFO  coverm] Using min-covered-fraction 0%
[2021-05-31T07:26:23Z INFO  bird_tool_utils::external_command_checker] Found minimap2 version 2.17-r941
[2021-05-31T07:26:25Z INFO  bird_tool_utils::external_command_checker] Found samtools version 1.12
[2021-05-31T07:26:25Z INFO  coverm] Not pre-generating minimap2 index
[2021-06-02T05:34:48Z ERROR coverm::bam_generator] Failed to correctly find or parse BAM file at "/tmp/coverm_fifo.Ahjh2FK9Mpns/foo.pipe": unable to open SAM/BAM/CRAM file at /tmp/coverm_fifo.Ahjh2FK9Mpns/foo.pipe
[2021-06-02T05:34:48Z ERROR coverm::bam_generator] Error when running mapping process. Exitstatus was ExitStatus(ExitStatus(256)). Command run was: ["bash -c \"set -e -o pipefail; minimap2 --split-prefix /tmp/.tmpMFhZK0 -a -x sr  -t 8  \'/scratch/users/sbusi/rocks/coassembly/binning/data/coassembly.final.contigs.fa\' \'/scratch/users/sbusi/rocks/coassembly/binning/data/coassembly.R1.preprocessed.fastq.gz\' \'/scratch/users/sbusi/rocks/coassembly/binning/data/coassembly.R2.preprocessed.fastq.gz\' 2>/tmp/.tmpsaBZe5  | remove_minimap2_duplicated_headers 2>/tmp/.tmpDH8hq1| samtools sort -T \'/tmp/coverm_fifo.Ahjh2FK9Mpns/coverm-make-samtools-sortH7oDyc\' -l0 -@ 7 2>/tmp/.tmpmgGKhO > \"/tmp/coverm_fifo.Ahjh2FK9Mpns/foo.pipe\"\""]
[2021-06-02T05:34:48Z ERROR coverm::bam_generator] The STDERR for the MINIMAP2_SR part was: [M::mm_idx_gen::78.646*1.66] collected minimizers
    [M::mm_idx_gen::85.227*2.13] sorted minimizers
    [M::main::85.227*2.13] loaded/built the index for 1696139 target sequence(s)
    [M::mm_mapopt_update::85.227*2.13] mid_occ = 1000
    [M::mm_idx_stat] kmer size: 21; skip: 11; is_hpc: 0; #seq: 1696139
    [M::mm_idx_stat::95.330*2.01] distinct minimizers: 619552179 (95.45% are singletons); average occurrences: 1.066; average spacing: 6.060
````
Is there another resolution for this?

Thank you!

**Comment by wwood** [comment]
I wonder if you are running out of RAM.

**Comment by susheelbhanu** [comment]
I checked and it only used 76.4% of the RAM allocated. Even supplied more CPUs cos was wondering the same thing.

**Comment by wwood** [comment]
Hmm, I'm not sure sorry. The main branch of coverm now no longer uses `remove_minimap2_duplicated_headers` but requires minimap2 2.20 - you could try that. However my suspicion is still that it is running out of RAM - does it give a different result when you request say double the RAM in your (PBS?) queue submission?

**Comment by susheelbhanu** [comment]
No worries. I certainly haven't doubled the RAM yet but I'll try it with minimap-2.20 and see if it helps. It very well could be the RAM, and if it is I'll keep you posted. Thanks for the pointers!

**Comment by AnupamGautam** [comment]
Hi @wwood,

I'm experiencing the same issue and have tried reinstalling multiple times. The allocated RAM is 500 GB, and I also attempted using an older version of minimap2, but the issue persists. I'm attaching the log here for your reference.

Thanks for your help!

Best regards,
Anupam
[coverm-3159560_4294967294.err.txt](https://github.com/user-attachments/files/17607016/coverm-3159560_4294967294.err.txt)

**Comment by wwood** [comment]
Hi @AnupamGautam I think your error might be due to this:
```
[E::bam_hdr_write] Header too long for BAM format
```
Basically, your reference sequences file is huge, too big for samtools. I'm not sure how to deal with this - what is the reference set?

**Comment by AnupamGautam** [comment]
Hi @wwood,

Thank you for your help! I initially thought the header wouldn’t be an issue since previous files ran perfectly without any problems.

However, I’m currently using output from Prodigal, which generates headers with space-separated start and stop positions along with additional information. To keep the full information intact, I replaced spaces with `#`, but this might have made the headers too large to fit within the maximum bit size allocated for headers in the BAM format. I’ll try making them shorter and re-run the process to see if this resolves the issue.

I’ll keep you posted on the results.

Thanks again!

Best regards,
Anupam

**Comment by AnupamGautam** [comment]
Hi @wwood,

The issue was resolved by reducing the header length. Thank you for the help!

Best regards,  
Anupam
